In [1]:
import numpy as np

In [8]:
# 求对角矩阵的特征值与特征向量
x=np.diag([1,2,3])
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [9]:
a,b=np.linalg.eig(x)
print("特征值",a)
print("特征向量",b)

特征值 [1. 2. 3.]
特征向量 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 获取矩阵的对角阵
x=np.arange(10,19).reshape([3,3])
print(x)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [11]:
y=np.diag(x)
print(y)

[10 14 18]


In [14]:
z=np.diag(y)
print(z)

[[10  0  0]
 [ 0 14  0]
 [ 0  0 18]]


In [16]:
# 求逆矩阵
x=np.array([[1,-2,1],[0,2,-1],[1,1,-2]])
print(x)

[[ 1 -2  1]
 [ 0  2 -1]
 [ 1  1 -2]]


In [34]:
y=np.linalg.inv(x)
print(y)
E=np.dot(y,x)
print(E)

[[ 1.          1.          0.        ]
 [ 0.33333333  1.         -0.33333333]
 [ 0.66666667  1.         -0.66666667]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 0.00000000e+00  1.11022302e-16  1.00000000e+00]]


In [18]:
# 求方阵的行列式值
z=np.linalg.det(x)
print(z)

-3.0000000000000004


In [19]:
# 求伴随矩阵
adjoint=y*z
print(adjoint)

[[-3. -3. -0.]
 [-1. -3.  1.]
 [-2. -3.  2.]]


In [ ]:
A=np.array([[1,-1],[1,1]])
B=np.linalg.inv(A)
E=np.dot(B,A)
print(E)

In [37]:
a=np.array([[0,1],[1,0]])
print(a)

[[0 1]
 [1 0]]


In [38]:
b=np.array([[1,1],[1,1]])
print(b)

[[1 1]
 [1 1]]


In [39]:
c=a-b
print(c)

[[-1  0]
 [ 0 -1]]


In [40]:
d=np.dot(c,c)
print(d)

[[1 0]
 [0 1]]


In [41]:
e=np.trace(d)
print(e)

2


In [42]:
print(e**0.5)

1.4142135623730951


In [46]:
# 欧几里得距离
x=np.random.random(10)
y=np.random.random(10)
dist1=np.linalg.norm(x-y)
dist2=np.sqrt(np.sum(np.square(x-y)))
print(dist1)
print(dist2)

1.289286116873096
1.289286116873096
